# Generated by Django 5.1.4 on 2024-12-06 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('sales', models.FloatField()),
                ('order_date', models.DateField()),
                ('discount', models.FloatField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
